### ISSUE TITLE
Error: EEXIST: file already exists, mkdir '/home/circleci/cypress_tests/reports'

### ISSUE THREAD

**Issue by boris-lapouga** [ksocha/cypress-circleci-reporter#5]
Hi,

I'm using this reporter with my CircleCI config and getting an error that is triggered by your line at
https://github.com/ksocha/cypress-circleci-reporter/blob/99b1b93a009f62b035e6ce9b371107b99770a089/src/index.ts#L108

I don't understand why it tries to create resultsDir, even when I provide it with a path, and when I do, it says it already exists, because it still tries to create it. As you can see, I have my steps for storing Cypress tests and no need a plugin to try and create more paths, I could make a PR, but not sure if forcing mkdir in your code has a purpose, so just raising an issue for now.

Example errors:

Nothing is provided as resultsDir:
[here](https://i.imgur.com/6b9f6M6.png)

Full path provided:
[here](https://i.imgur.com/2LZzfOW.png)

My config:

```
version: 2.1

aliases:
  - &persist_to_workspace
    persist_to_workspace:
      root: /home/circleci/join-test
      paths: ["cypress_tests"]
  - &attach_workspace
    attach_workspace:
      at: /home/circleci/join-test
  
executors:
  browsers:
    docker:
      - image: circleci/node:12.6-browsers
    working_directory: /home/circleci/join-test
      
commands:
  auth_cypress_with_registry:
    steps:
      - run:
          name: Authenticate with registry
          command: cd cypress_tests && echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > .npmrc
  npm_ci:
    steps:
      - run:
          name: Install dependencies (npm ci)
          command: cd cypress_tests && npm ci
  save_cypress_cache:
    steps:
      - save_cache:
          key: dep2-{{ .Branch }}-cache-{{ checksum "cypress_tests/package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache/Cypress
  restore_cypress_cache:
    steps:
      - restore_cache:
          key: dep2-{{ .Branch }}-cache-{{ checksum "cypress_tests/package-lock.json" }}
  run_cypress_all:
    steps:
      - restore_cypress_cache
      - run:
          name: Run all cypress tests in parallel
          no_output_timeout: 5m
          command: |
            cd cypress_tests && npx cypress run --spec "$(circleci tests glob "./cypress/integration/**/*.feature" | circleci tests split --split-by=timings --timings-type=filename | paste -sd "," -)" --reporter cypress-circleci-reporter --reporter-options resultsDir=results resultsFileName=cypress-$CIRCLE_BUILD_NUM
  store_cypress_test_results:
    steps:
      - store_test_results:
          path: cypress_tests/reports
      - store_artifacts:
          path: cypress_tests/reports
          destination: cypress/reports
      - store_artifacts:
          path: cypress_tests/cypress/videos
          destination: cypress/videos
      - store_artifacts:
          path: cypress_tests/cypress/screenshots
          destination: cypress/screenshots
   
jobs:
  build_cypress:
    executor: browsers
    steps:
      - checkout
      - restore_cypress_cache
      - auth_cypress_with_registry
      - npm_ci
      - run:
          name: cypress install
          command: cd cypress_tests && npx cypress install
      - save_cypress_cache
      - *persist_to_workspace
  pr_all:
    executor: browsers
    parallelism: 20
    steps:
      - *attach_workspace
      - run_cypress_all
      - store_cypress_test_results
  lint:
    working_directory: /home/circleci/join-test
    docker:
      - image: circleci/node:12.6
    steps:
      - checkout
      - restore_cypress_cache
      - auth_cypress_with_registry
      - npm_ci
      - run:
          name: lint cypress
          command: cd cypress_tests && npm run lint
      - run:
          name: check types cypress
          command: cd cypress_tests && npm run ts:check
      - run:
          name: lint tags
          command: cd cypress_tests && node scripts/validate_tags.js
          
workflows:
  version: 2
  build_test:
    jobs:
      - lint
      - build_cypress
      - pr_all:
          requires:
            - build_cypress
```
